apiVersion:  apps/v1
kind: Deployment
metadata:
    name: my-deploymen
spec:
  replicas: 3
  strategy:   
    type: RollingUpdate
    rollingUpdate:
         maxSurge: 50%
         maxUnavalilable: 0
  selector:
      matchLabels:
           env: prod      
 
  template:
      metadata:
         labels:
             env: prod
      spec:
         containers:
           - name: deply-c1
             image: nginx    
