apiVersion: v1
kind: ReplicationController 
metadata:
  name: my-rc
spec:
   replicas: 3
   template:
    metadata:
      name: my-new-pod-rc
      labels:
        env: prod
        dc: hyd
    spec:
      containers:
         - name: c1-rc
           image: nginx
                            

