apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment  # Corrected name
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%          # This can be a percentage or an absolute number
      maxUnavailable: 0      # Corrected key
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: deploy-c1     # Corrected container name
          image: nginx:1.14.2

